[package]

name = "rhex"
version = "0.0.1"
authors = ["Dawid Ciężarkiewicz <dpc@ucore.info>"]

[profile.dev]
opt-level = 1
debug = true
lto = false
debug-assertions = true


[dependencies]
num = "*"
rand = "*"
time = "*"
hex2d = "*"
hex2d-dpcext = { git = "https://github.com/dpc/hex2d-dpcext-rs" }
log = "*"
fern = "*"
schedule_recv = "*"
ncurses = "*"
dpc-simplemap = "*"
fnv = "*"
