[package]

name = "rhex"
version = "0.0.1"
authors = ["Dawid Ciężarkiewicz <dpc@ucore.info>"]

[dependencies]
num = "*"
rand = "*"
time = "*"
hex2d = "*"
hex2d-dpcext = "*"
log = "*"
fern = "*"
schedule_recv = "*"
ncurses = "*"
dpc-simplemap = "*"
fnv = "*"
