[package]

name = "rhex"
version = "0.0.1"
authors = ["Dawid Ciężarkiewicz <dpc@ucore.info>"]

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs.git"

[dependencies]
num = "*"
rand = "*"
time = "*"
hex2d = "*"
hex2d-dpcext = "*"
log = "*"
fern = "*"

[dependencies.schedule_recv]
git = "https://github.com/PeterReid/schedule_recv.git"
